# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{crud_star}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Steve Lorek"]
  s.date = %q{2010-09-23}
  s.description = %q{CrudStar}
  s.email = %q{steve@stevelorek.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "app/controllers/crud_star/account_controller.rb",
     "app/controllers/crud_star/admin_controller.rb",
     "app/controllers/crud_star/crud_controller.rb",
     "app/controllers/crud_star/index_controller.rb",
     "app/controllers/crud_star/test_controller.rb",
     "app/helpers/crud_star/admin_helper.rb",
     "app/helpers/crud_star/remote_link_renderer.rb",
     "app/models/crud_star/user.rb",
     "app/views/crud_star/_edit_associated.html.erb",
     "app/views/crud_star/_errors.html.erb",
     "app/views/crud_star/_list.html.erb",
     "app/views/crud_star/_list_associated.html.erb",
     "app/views/crud_star/_list_filter.html.erb",
     "app/views/crud_star/_list_item.html.erb",
     "app/views/crud_star/_new_associated.html.erb",
     "app/views/crud_star/account/login.html.erb",
     "app/views/crud_star/edit.html.erb",
     "app/views/crud_star/index.csv.erb",
     "app/views/crud_star/index.html.erb",
     "app/views/crud_star/index/index.html.erb",
     "app/views/crud_star/new.html.erb",
     "app/views/crud_star/show.html.erb",
     "app/views/layouts/crud_star.html.erb",
     "config/routes.rb",
     "lib/crud_star.rb",
     "lib/crud_star/acts_as_crud_star/base.rb",
     "lib/crud_star/engine.rb",
     "lib/rails/generators/crud_star/crud_star_config_generator.rb",
     "lib/rails/generators/crud_star/templates/initializer.rb",
     "public/images/crud_star/ajax_loading.gif",
     "public/images/crud_star/body-bg.jpg",
     "public/images/crud_star/bullet-blue.gif",
     "public/images/crud_star/bullet-green.gif",
     "public/images/crud_star/bullet-orange.gif",
     "public/images/crud_star/bullet-pink.gif",
     "public/images/crud_star/bullet-purple.gif",
     "public/images/crud_star/bullet-red.gif",
     "public/images/crud_star/bullet-yellow.gif",
     "public/images/crud_star/header-logo-blue.jpg",
     "public/images/crud_star/header-logo-fairline.jpg",
     "public/images/crud_star/header-logo-green.jpg",
     "public/images/crud_star/header-logo-orange.jpg",
     "public/images/crud_star/header-logo-pink.jpg",
     "public/images/crud_star/header-logo-purple.jpg",
     "public/images/crud_star/header-logo-red.jpg",
     "public/images/crud_star/header-logo-yellow.jpg",
     "public/images/crud_star/icon-alert.gif",
     "public/images/crud_star/icon-delete.gif",
     "public/images/crud_star/icon-down-disabled.png",
     "public/images/crud_star/icon-down.png",
     "public/images/crud_star/icon-edit.gif",
     "public/images/crud_star/icon-expanded.gif",
     "public/images/crud_star/icon-expanded.png",
     "public/images/crud_star/icon-ok.gif",
     "public/images/crud_star/icon-up-disabled.png",
     "public/images/crud_star/icon-up.png",
     "public/images/crud_star/icon-user-blue.png",
     "public/images/crud_star/icon-user-green.png",
     "public/images/crud_star/icon-user-orange.png",
     "public/images/crud_star/icon-user-pink.png",
     "public/images/crud_star/icon-user-purple.png",
     "public/images/crud_star/icon-user-red.png",
     "public/images/crud_star/icon-user-yellow.png",
     "public/images/crud_star/icon-wrong.gif",
     "public/images/crud_star/menu-bg-blue.jpg",
     "public/images/crud_star/menu-bg-green.jpg",
     "public/images/crud_star/menu-bg-orange.jpg",
     "public/images/crud_star/menu-bg-pink.jpg",
     "public/images/crud_star/menu-bg-purple.jpg",
     "public/images/crud_star/menu-bg-red.jpg",
     "public/images/crud_star/menu-bg-yellow.jpg",
     "public/images/crud_star/menu-tab-bg.jpg",
     "public/images/crud_star/sidebar-header.jpg",
     "public/images/crud_star/sort_asc.gif",
     "public/images/crud_star/sort_desc.gif",
     "public/images/crud_star/submenu-bg.jpg",
     "public/images/crud_star/tralt-bg.jpg",
     "public/javascripts/crud_star/application.js",
     "public/stylesheets/crud_star/admin.css",
     "public/stylesheets/crud_star/blue.css",
     "public/stylesheets/crud_star/green.css",
     "public/stylesheets/crud_star/ie6.css",
     "public/stylesheets/crud_star/orange.css",
     "public/stylesheets/crud_star/pink.css",
     "public/stylesheets/crud_star/purple.css",
     "public/stylesheets/crud_star/red.css",
     "public/stylesheets/crud_star/reset.css",
     "public/stylesheets/crud_star/yellow.css"
  ]
  s.homepage = %q{http://github.com/slorek/crud_star}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{CrudStar}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<will_paginate>, [">= 3.0.pre2"])
    else
      s.add_dependency(%q<will_paginate>, [">= 3.0.pre2"])
    end
  else
    s.add_dependency(%q<will_paginate>, [">= 3.0.pre2"])
  end
end

